### PR TITLE
Release tridesclous 1.4.1

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeremy,
sorry for this cascade of release.
I take my last chance to have decent benchmark before the paper....
I hope this do not give too much for you.
very sorry.

Cheers,

Samuel

**Comment by magland** [comment]
No worries at all. Thanks for the effort, which benefits SpikeForest!

**Comment by samuelgarcia** [comment]
I did not change the docker.
Does the previous test was on a Node with GPU capabilities ?

**Comment by magland** [comment]
I added GPU capability and it works okay. But for the tetrode example, the accuracy was low. Here's the output of the test

There is one warning:

```
Warning PruningShears reach max_loop limit there are maybe more cluster
```

Entire output:
```
===== Hither: running [tridesclous] in container: docker://magland/sf-tridesclous:1.4.1
#############################################################

                #!/bin/bash

                exec singularity exec -e --nv \
                    -B $KACHERY_STORAGE_DIR:/kachery-storage \
                    -B /home/magland/kachery-storage/tmp/tmp_hither_run_in_container_tridesclous_xaugdqh6:/run_in_container \
                    -B /home/magland/kachery-storage/tmp/tmp_hither_run_in_container_tridesclous_xaugdqh6/outputs:/outputs \
                    docker://magland/sf-tridesclous:1.4.1 \
                    bash /run_in_container/run.sh
            
#############################################################
tridesclous 2019-12-20T08:27:16.190358: ###### RUNNING: tridesclous

libgomp: Invalid value for environment variable OMP_NUM_THREADS
tridesclous 2019-12-20T08:27:18.186997: Sorting...
tridesclous 2019-12-20T08:31:29.732460: Warning PruningShears reach max_loop limit there are maybe more cluster
tridesclous 2019-12-20T08:31:35.608188: #SF-SORTER-RUNTIME#256.762#
===== Hither: finished [tridesclous] with status finished after 259.4210910797119 sec
===== Hither: Building singularity container: docker://magland/spikeforest2:0.1.0
built docker://magland/spikeforest2:0.1.0
===== Hither: running [compare_with_truth] in container: docker://magland/spikeforest2:0.1.0
#############################################################

                #!/bin/bash

                exec singularity exec -e  \
                    -B $KACHERY_STORAGE_DIR:/kachery-storage \
                    -B /home/magland/kachery-storage/tmp/tmp_hither_run_in_container_compare_with_truth_1_7lwnh5:/run_in_container \
                    -B /home/magland/kachery-storage/sha1/cc/e4/28/cce42806bcfe86f4f58c51aefb61f2c28a99f6cf:/inputs/sorting_true_path.json -B /home/magland/kachery-storage/sha1/5e/42/9b/5e429b2dba81b290fb66ee1b5ea075108fc7d64c:/inputs/sorting_path -B /home/magland/kachery-storage/tmp/tmp_hither_run_in_container_compare_with_truth_1_7lwnh5/outputs:/outputs \
                    docker://magland/spikeforest2:0.1.0 \
                    bash /run_in_container/run.sh
            
#############################################################
compare_with_truth 2019-12-20T08:31:37.730854: ###### RUNNING: compare_with_truth
===== Hither: finished [compare_with_truth] with status finished after 0.026543617248535156 sec
AVERAGE-ACCURACY: 0.10512999999999999
Passed.
```

**Comment by samuelgarcia** [comment]
The GPU is a good news.
Are retust online ?

Which results give this warning. It is indeed a big problem that kill enchmark.
In tetrode this is very strange. Is it a dataset I can download to test locally ?

**Pull request merged**
