### PR TITLE
Release tridesclous 1.4.0

### PR DESCRIPTION
**Pull request by samuelgarcia**
Hi Jeremy,
here some patch for the relase of tridesclous 1.4.0
This should fix the bug.
I take a chance with opencl in docker.

Tell if it works.

I can't test I am at home with GPU.

Cheers,

Samuel

### CODE REVIEW

**Comment by magland** [comment]
thx, i will test.

**Comment by samuelgarcia** [comment]
Oups I forgot to change version in the decorator of the wrapper.
Sorry.

**Comment by magland** [comment]
the docker image builds, and it runs on a tetrode (giving low accuracy) and then for a 32c example, I get the following error:

```
tridesclous 2019-12-19T14:08:03.223659: Traceback (most recent call last):
tridesclous 2019-12-19T14:08:03.223699:   File "/run_in_container/run.py", line 15, in main
tridesclous 2019-12-19T14:08:03.223704:     retval = tridesclous(**kwargs)
tridesclous 2019-12-19T14:08:03.223711:   File "/run_in_container/function_src/_tridesclous.py", line 36, in tridesclous
tridesclous 2019-12-19T14:08:03.223715:     timer = sorter.run()
tridesclous 2019-12-19T14:08:03.223721:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/basesorter.py", line 110, in run
tridesclous 2019-12-19T14:08:03.223724:     self._run(recording, self.output_folders[i])
tridesclous 2019-12-19T14:08:03.223730:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/tridesclous/tridesclous.py", line 153, in _run
tridesclous 2019-12-19T14:08:03.223734:     tdc.apply_all_catalogue_steps(cc, catalogue_nested_params, verbose=self.verbose)
tridesclous 2019-12-19T14:08:03.223740:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/cataloguetools.py", line 89, in apply_all_catalogue_steps
tridesclous 2019-12-19T14:08:03.223744:     cc.set_peak_detector_params(**d)
tridesclous 2019-12-19T14:08:03.223749:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/catalogueconstructor.py", line 474, in set_peak_detector_params
tridesclous 2019-12-19T14:08:03.223753:     self.peakdetector.change_params(**p)
tridesclous 2019-12-19T14:08:03.223759:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/peakdetector.py", line 466, in change_params
tridesclous 2019-12-19T14:08:03.223763:     OpenCL_Helper.initialize_opencl(self, cl_platform_index=cl_platform_index, cl_device_index=cl_device_index)
tridesclous 2019-12-19T14:08:03.223769:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/cltools.py", line 42, in initialize_opencl
tridesclous 2019-12-19T14:08:03.223773:     self.ctx = pyopencl.create_some_context(interactive=False)
tridesclous 2019-12-19T14:08:03.223778:   File "/usr/local/lib/python3.6/dist-packages/pyopencl/__init__.py", line 1385, in create_some_context
tridesclous 2019-12-19T14:08:03.223782:     platforms = get_platforms()
tridesclous 2019-12-19T14:08:03.223793: pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
```

**Comment by samuelgarcia** [comment]
Oups.
It means that there is no opencl device on the machine.
What the command "clinfo give ?
Did you run this on node with GPU.
If I remember correctly sorter that run on GPU nodes are harcoded somewhere in the main script and there were only KS and IC.

**Pull request merged**
