### PR TITLE
Wrong param file used for SC

### PR DESCRIPTION
**Pull request by yger**
Code is running, and despite the fact that it is searching for container with 0.8.6 version, code inside is 0.8.8, so it looks fine. However, the parameter file used is not up to date, I guess because spikesorters needs to be updated

### CODE REVIEW

**Comment by yger** [comment]
Still not able to get the proper parameter file, so I guess something is wrong with my container and spikesorters version

**Comment by magland** [comment]
Do you think the current version of spikesorters (master branch) has
the correct code? If so, we should point to that rather than pypi in the
docker container.

**Comment by yger** [comment]
yes, at least on my desktop machine, with the masterbranch of spikesorters, the param file is correct. I don't know why, however, this is not the case in the container (since the docker looks correct). But since I'm not an expert with docker, maybe I made a mistake somehow. i'll double check

**Comment by magland** [comment]
There's a difference between the master branch:
https://github.com/SpikeInterface/spikesorters/tree/master/spikesorters/spyking_circus
and the tagged version 0.2.1:
https://github.com/SpikeInterface/spikesorters/tree/0.2.1/spikesorters/spyking_circus
<https://github.com/SpikeInterface/spikesorters/tree/0.2.2/spikesorters/spyking_circus>
referred to in the docker.

Maybe we need 0.2.2 -- or grab it from master. In the latter case we should
point to a particular commit.

**Comment by yger** [comment]
But as you pointed out, with the 0.2.2 tag, the param file is correct
https://github.com/SpikeInterface/spikesorters/blob/0.2.2/spikesorters/spyking_circus/config_default.params. I've added in the docker
RUN pip install spikeextractors==0.7.0 spiketoolkit==0.5.0 spikesorters==0.2.2
I thought it should work, but maybe I did something wrong here

**Comment by magland** [comment]
My version still has 0.2.1, so in the cloud 0.8.8 has 0.2.1. You should tag
it differently locally so that there's not chance of conflict.

**Comment by magland** [comment]
I just updated my Dockerfile to use ss 0.2.2 and tagged a new container
0.8.8b and updated the wrapper.

**Comment by magland** [comment]
There was still a problem so I also upgraded the versions of
spikeextractors and spiketoolkit in the dockerfile. Hoping that will fix it
and testing now.

**Comment by magland** [comment]
@yger I merged this and created the docker image. The test seems to work. Is this good to go, or do I need to wait for something to change on spikeinterface?

**Pull request merged**
