### PR TITLE
Release tridesclous 1.6.0

### PR DESCRIPTION
**Pull request by samuelgarcia**
Hi Jeremy.
here a patch for tridesclous 1.6.0
In this release there more opencl kernel that could bug.
Tell if it works.
I push the docker to my account.
I don't known you want to build your own.

Cheers
Samuel

### CODE REVIEW

**Comment by magland** [comment]
Thanks! This will take effect in our next run.

(@jsoules - let's launch this run together tomorrow.)

**Comment by samuelgarcia** [comment]
thank you very much.
Tell me when done.
I am interested in run times with opencl.

**Comment by samuelgarcia** [comment]
Hi Jeremy,
did you finally  launch another run ?
Cheers
Samuel

**Comment by magland** [comment]
Working on that now... one of our databases needs to be resurrected.

**Comment by samuelgarcia** [comment]
Thanks a lot.

**Pull request merged**
