### PR TITLE
Changed versions to reflect latest HS release

### PR DESCRIPTION
**Pull request by mhhennig**

### CODE REVIEW

**Comment by magland** [comment]
Prior to merging, we will also need to increment the version of the wrapper and container in the following three files:

https://github.com/flatironinstitute/spikeforest2/blob/master/spikeforest2/sorters/herdingspikes2/_herdingspikes2.py
https://github.com/flatironinstitute/spikeforest2/blob/master/spikeforest2/sorters/herdingspikes2/container/build_docker.sh
https://github.com/flatironinstitute/spikeforest2/blob/master/spikeforest2/sorters/herdingspikes2/container/push_docker.sh

Would you like me to do that @mhhennig?

**Comment by magland** [comment]
Thx. Merging. Then I will build the container from my end.

**Comment by mhhennig** [comment]
Just did it. In this one:

https://github.com/mhhennig/spikeforest2/blob/patch-1/spikeforest2/sorters/herdingspikes2/_herdingspikes2.py

There was a `-w1` in `@hither.function('herdingspikes2', '0.3.X7-w1')` - I left it, is it correct?

**Comment by magland** [comment]
Yes, that just means it's version 1 of the wrapper corresponding to that release version of the sorter -- in case we change the wrapper but not the release version.

**Pull request merged**
