### PR TITLE
Prepare release tridesclous 1.4.2

### PR DESCRIPTION
**Pull request by samuelgarcia**
prepare tridesclous release 1.4.2

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeremy.
tridesclous 1.4.2 is out.
Here the patch for SF2.
Tell me if it is OK.

**Comment by magland** [comment]
Looks good to me... except I would suggest that you redirect the docker image to your own dockerhub. If that is problematic for you, then I will be happy to do it on my end.

@samuelgarcia

**Comment by samuelgarcia** [comment]
I don't have dockerhub account.
I can have a look and try to create it.

**Comment by magland** [comment]
If you are interested, you can do that. Then it is just a matter of
changing magland->[your-user-name] in the scripts. And you also need to do
`docker login` on the command line. Then just run the scripts.

Again, if you encounter difficulty, let me know and I will push to magland
dockerhub

**Comment by samuelgarcia** [comment]
OK
I did all change and left you repo commented.
I build the image and push it.
Thank you for the help.
Lets see if it works.

**Comment by magland** [comment]
I pulled and ran test_tridesclous_tetrode.py inside working/tests and it ran!

I notice a lot more verbose output. The accuracy (for that tetrode) and time spent is similar to what it was prior to the merge. So good news!

**Comment by samuelgarcia** [comment]
Yes I put verbose=tre in the wrapper because in the new SF2 you do verbose=false by default.

It help me a lot to understand run times and results to hae the full verbose with the console in the website.

**Pull request merged**
