### PR TITLE
Bumping version to SC 0.8.8

### PR DESCRIPTION
**Pull request by yger**
I can not make it run yet, but at least, I guess this should be updated

### CODE REVIEW

**Comment by magland** [comment]
Thx, merging. Do you get an error when you try to run?

**Comment by magland** [comment]
(BTW, I added "RUN pip install cmake scikit-build" to the dockerfile prior to install of spyking circus)

**Comment by yger** [comment]
No, no errors, but when launching the .py example, I can see that the code is still trying to download 0.8.6:
 
Unable to find image 'magland/sf-spykingcircus:0.8.6' locally

I guess this is temporary, until you update the container somewhere in the cloud. However, as said in my email, I can not install spikeforest_widgets

**Comment by magland** [comment]
It should be trying to grab 0.8.8, and that should be in the cloud:
https://hub.docker.com/r/magland/sf-spykingcircus/tags

**Pull request merged**
