### PR TITLE
Prepare for 0.9.5 that should be faster, without timeouts

### PR DESCRIPTION
**Pull request by yger**
No hurry for propagating these changes, but I made an incremental release, 0.9.5, that should be faster when used with SpikeInterface. In theory, this should not impact performances too much (let's cross fingers), but my goal was on the SF website to not have any more timeouts, which should be the case here. 
By the way, how can I know if missing values are due to timeouts or errors? With the new SF2, I can not really access to the logs of the failed run, can I? I'm just curious since I would like to be sure the software can run in all cases

### CODE REVIEW

**Comment by magland** [comment]
Yes, you can see the logs and there is a field that tells whether it timed out. For example,
http://spikeforest.flatironinstitute.org/sortingresult/paired_crcns/d18021_d18021.004/SpykingCircus

It's a bit hidden, but you can drill down to find it on the website.

@lizlove we should think about how to make the sorting result view easier to find.

**Comment by yger** [comment]
But how can tell if it really timed out, or if the software crashed with an error message, then get stucked? We can not get the full log, can we? In a nutshell, how do we tell if it timed out because of an error or because of time per se?

**Comment by magland** [comment]
That's a good question. In fact it seems like that particular example in the above link crashed rather than timed out. Not sure why the system then hung for a long duration, because the crash seems to have happened after only a few seconds:

```
spykingcircus 2020-02-20T11:30:39.317001: ###### RUNNING: spykingcircus:paired_crcns/d18021_d18021.004
spykingcircus 2020-02-20T11:30:41.667026: Sorting...
spykingcircus 2020-02-20T11:30:43.333400: RUNNING SHELL SCRIPT: /tmp/tmp_shellscriptsazc05p7/script.sh
spykingcircus 2020-02-20T12:30:38.034581: Traceback (most recent call last):
spykingcircus 2020-02-20T12:30:38.034666:   File "/run_in_container/run.py", line 15, in main
spykingcircus 2020-02-20T12:30:38.034675:     retval = spykingcircus(**kwargs)
spykingcircus 2020-02-20T12:30:38.034685:   File "/run_in_container/function_src/_spykingcircus.py", line 53, in spykingcircus
spykingcircus 2020-02-20T12:30:38.034689:     timer = sorter.run()
spykingcircus 2020-02-20T12:30:38.034697:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/basesorter.py", line 137, in run
spykingcircus 2020-02-20T12:30:38.034702:     self._run(recording, self.output_folders[i])
spykingcircus 2020-02-20T12:30:38.034709:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/spyking_circus/spyking_circus.py", line 149, in _run
spykingcircus 2020-02-20T12:30:38.034716:     raise Exception('spykingcircus returned a non-zero exit code')
spykingcircus 2020-02-20T12:30:38.034742: Exception: spykingcircus returned a non-zero exit code
```

I guess we need to look into that a bit further.

**Comment by magland** [comment]
Oh no, I misread it. It was a timeout. I was tricked because it happened an hour later.

But I don't see console output for SC itself. The non-zero exit code is deceptive. I think the system kills it after an hour, causing the non-zero exit code.

So, in summary, still inconclusive. But someone should run that example offline.

**Comment by magland** [comment]
I am trying it now based on the reproducing code on the website. Seems to run without trouble, so I'm not sure what the issue was.

**Comment by yger** [comment]
To be honest, I think the timeouts are weird on small dataset. While I could understand some for large dataset (but this should be solved by 0.9.5, as this puzzled me), this is strange to see so many. The code should be fairly robust and work in all cases. Or if not, at least it would be interesting to have a more informative log/error. Thanks again for your work, this is really helping us to push the limit of the software!

**Comment by yger** [comment]
And just a side note: I tried, as you suggested, to run the code snippet found here http://spikeforest.flatironinstitute.org/sortingresult/paired_crcns/d18021_d18021.004/SpykingCircus
But this is not working, as it looks like I can not download the raw data. (the url is not found, thus leading to a crash with the SF2 pipeline)

**Comment by yger** [comment]
Alors, regarding the performance for monotrode, I suspect something is weird in SF. I would like to be able to download one dataset in order to understand what, as this is unlikely that our scores are correct. Unfortunately, it seems that links to download monotrode experiments are not working also, so I can not help you to debug :-(

**Comment by magland** [comment]
Our servers are down for maintenance right now. I expect it should be back online in a few days.

**Comment by magland** [comment]
Actually servers are up now. Could you try? Starting tomorrow, they will be down for maintenance for a few days.

**Comment by yger** [comment]
This is working for the paired_crcns ('sha1dir://779d96521176077ec260ef99573dea3b772c74e6.paired_crcns/d18021_d18021.004')

But when trying to download a monotrode recording (like the one fro Quiroga, to understand what could go wrong sa badly for us), I get
 Unable to realize file: sha1dir://d857ca61ee229a341ff44ebaa7e299b4a401c066.synth_monotrode/quiroga_easy1/C_Easy1_noise005/raw.mda

No hurry, this is just because I'm curious to debug everything, in order to have a clean column in SF (no timeouts, and if possible no obvious mistakes...)

**Comment by magland** [comment]
Maybe you are not using the most up-to-date system for downloading data?

You can `pip install kachery` and then

```
> kachery-info
sha1dir://d857ca61ee229a341ff44ebaa7e299b4a401c066.synth_monotrode/quiroga_easy1/C_Easy1_noise005/raw.mda
--fr default_readonly
```

I can find it on my end. See the code for reproducing that's published on
the website for more info.

J

**Comment by yger** [comment]
Could be, thanks for the tip as I did not check. If this is working for
you, it has to work for me too!

**Comment by magland** [comment]
FYI, I just learned they are actually pulling the servers down for
maintenance today. :)

**Comment by yger** [comment]
Let me know when they are back online, since I was not able to download it, even with kachery upgrade. And no need to run everything with 0.9.5, wait for a 0.9.6 release, still faster, since I'm refactoring heavily the code to gain speed, trying to keep the performances untouched. Save computer time if you want :-), I'll upgrade this PR soon once for all and you can relaunch everything.  I know I'm releasing too often, sorry for that, but most of our users are using conda and like tagged releases...

**Comment by yger** [comment]
This is good for me, I hope I fixed everything, speed should not be a problem anymore and same with monotrode. Now let's hibernate because of Covid-19 :-(

**Comment by yger** [comment]
Any chances to see the results for this PR in SF? No hurry, work is rather slow these days, but I would like to be sure there are no more timeouts, with much faster execution times. Good luck and take care

**Comment by magland** [comment]
Thanks Pierre. I just merged the PR, and I am going to build the container so next time we update the website (in a day or 2) you should see the changes.

**Comment by yger** [comment]
Cool, no hurry. Just that I wanted to get rid of the timeouts, so worked
hard to speed up the code. Looking forward to see the results (and hoping
it won't degrade results too much :-( )

Le mar. 21 avr. 2020 à 16:01, Jeremy Magland <notifications@github.com> a
écrit :

**Pull request merged**
